# Generated by Django 4.1.7 on 2023-03-11 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_name', models.TextField(blank=True, null=True, verbose_name='아기이름')),
                ('birth', models.DateField(auto_now=True)),
                ('gender', models.CharField(default='N', max_length=1, verbose_name='성별')),
            ],
            options={
                'db_table': 'babyProfile',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(blank=True, null=True, verbose_name='사용자이름')),
                ('password', models.TextField(blank=True, null=True, verbose_name='비밀번호')),
                ('email', models.TextField(blank=True, null=True, verbose_name='이메일')),
                ('profile_img', models.FilePathField(blank=True, null=True, verbose_name='사용자이미지')),
                ('relation', models.CharField(default='N', max_length=1, verbose_name='관계')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userProfile',
            },
        ),
        migrations.CreateModel(
            name='UserBabyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lstm_api.babyprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lstm_api.userprofile')),
            ],
            options={
                'db_table': 'userBabyRelationship',
                'unique_together': {('user', 'baby')},
            },
        ),
        migrations.CreateModel(
            name='LifeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('mode', models.CharField(default='N', max_length=1, verbose_name='행위')),
                ('content', models.TextField(blank=True, null=True, verbose_name='기록내용')),
                ('baby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lstm_api.babyprofile')),
            ],
            options={
                'db_table': 'lifeLog',
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.TextField(blank=True, null=True, verbose_name='접종/검진 이력')),
                ('mode', models.CharField(default='N', max_length=1, verbose_name='예방접종/건강검진')),
                ('state', models.CharField(default='N', max_length=1, verbose_name='수행여부')),
                ('baby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lstm_api.babyprofile')),
            ],
            options={
                'db_table': 'healthCheck',
            },
        ),
        migrations.CreateModel(
            name='GrowthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='키')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='몸무게')),
                ('date', models.DateField(auto_now=True, verbose_name='날짜')),
                ('baby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lstm_api.babyprofile')),
            ],
            options={
                'db_table': 'growthLog',
            },
        ),
        migrations.AddField(
            model_name='babyprofile',
            name='user_baby_rel',
            field=models.ManyToManyField(through='lstm_api.UserBabyRelationship', to='lstm_api.userprofile'),
        ),
    ]
