# Generated by Django 3.2.18 on 2023-03-16 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('relation', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BabyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_name', models.TextField(blank=True, null=True, verbose_name='아기이름')),
                ('birth', models.TextField(blank=True, null=True, verbose_name='탄생일')),
                ('gender', models.CharField(default='N', max_length=1, verbose_name='성별')),
            ],
            options={
                'db_table': 'babyProfile',
            },
        ),
        migrations.CreateModel(
            name='UserBabyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lstm_api.babyprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userBabyRelationship',
                'unique_together': {('user', 'baby')},
            },
        ),
        migrations.CreateModel(
            name='LifeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('mode', models.CharField(default='N', max_length=1, verbose_name='행위')),
                ('content', models.TextField(blank=True, null=True, verbose_name='기록내용')),
                ('baby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lstm_api.babyprofile')),
            ],
            options={
                'db_table': 'lifeLog',
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.TextField(blank=True, null=True, verbose_name='접종/검진 이력')),
                ('mode', models.CharField(default='N', max_length=1, verbose_name='예방접종/건강검진')),
                ('state', models.CharField(default='N', max_length=1, verbose_name='수행여부')),
                ('baby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lstm_api.babyprofile')),
            ],
            options={
                'db_table': 'healthCheck',
            },
        ),
        migrations.CreateModel(
            name='GrowthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='키')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='몸무게')),
                ('date', models.DateField(auto_now=True, verbose_name='날짜')),
                ('baby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lstm_api.babyprofile')),
            ],
            options={
                'db_table': 'growthLog',
            },
        ),
        migrations.AddField(
            model_name='babyprofile',
            name='user_baby_rel',
            field=models.ManyToManyField(through='lstm_api.UserBabyRelationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
