# Generated by Django 3.2.18 on 2023-04-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstm_api', '0004_remove_user_relation_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbabyrelationship',
            name='access_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='날짜'),
        ),
        migrations.AddField(
            model_name='userbabyrelationship',
            name='access_endtime',
            field=models.TimeField(null=True, verbose_name='종료시간'),
        ),
        migrations.AddField(
            model_name='userbabyrelationship',
            name='access_starttime',
            field=models.TimeField(null=True, verbose_name='시작시간'),
        ),
        migrations.AlterField(
            model_name='userbabyrelationship',
            name='relation',
            field=models.IntegerField(blank=True, null=True, verbose_name='관계'),
        ),
    ]
