# Generated by Django 3.2.18 on 2023-04-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstm_api', '0005_auto_20230406_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbabyrelationship',
            name='relation',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='관계'),
        ),
    ]
