# Generated by Django 3.2.18 on 2023-04-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstm_api', '0007_userbabyrelationship_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyprofile',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='userbabyrelationship',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
