# Generated by Django 3.2.18 on 2023-04-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lstm_api', '0008_auto_20230414_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifelog',
            name='baby',
        ),
        migrations.AddField(
            model_name='lifelog',
            name='userbaby_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lstm_api.userbabyrelationship'),
        ),
    ]
