# Generated by Django 3.2.18 on 2023-04-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstm_api', '0009_auto_20230414_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcheck',
            name='mode',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='예방접종/건강검진'),
        ),
        migrations.AlterField(
            model_name='lifelog',
            name='mode',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='행위'),
        ),
    ]
