# Generated by Django 3.2.18 on 2023-04-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstm_api', '0010_auto_20230414_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babyprofile',
            name='ip',
        ),
        migrations.AddField(
            model_name='babyprofile',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL'),
        ),
    ]
