# Generated by Django 3.2.18 on 2023-04-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstm_api', '0011_auto_20230414_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthlog',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='키'),
        ),
        migrations.AlterField(
            model_name='growthlog',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='몸무게'),
        ),
    ]
