# Generated by Django 3.2.18 on 2023-05-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstm_api', '0012_auto_20230421_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheck',
            name='date',
            field=models.DateField(auto_now=True, null=True, verbose_name='날짜'),
        ),
    ]
